### ISSUE TITLE
Failed to lookup view "error" in views directory

### ISSUE THREAD

**Issue by kukuandroid** [tariqulislam/express-email-project#1]
Failed to lookup view "error" in views directory

**Comment by tariqulislam** [comment]
@kukuandroid , I will see that issue, Let you know when it's done. can you please give error log and little bit details about your issue.

**Comment by rbalakrishnan1994** [comment]
@tariqulislam  please find the error log.. 

Error: Failed to lookup view "error" in views directory "C:\Users\userpath\Documents\GitHub\express-email-project\views"
    at Function.render (C:\Users\userpath\Documents\GitHub\express-email-project\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (C:\Users\userpath\Documents\GitHub\express-email-project\node_modules\express\lib\response.js:1008:7)
    at C:\Users\userpath\Documents\GitHub\express-email-project\app.js:36:7
    at Layer.handle_error (C:\Users\userpath\Documents\GitHub\express-email-project\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\userpath\Documents\GitHub\express-email-project\node_modules\express\lib\router\index.js:315:13)
    at C:\Users\userpath\Documents\GitHub\express-email-project\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\userpath\Documents\GitHub\express-email-project\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\userpath\Documents\GitHub\express-email-project\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\userpath\Documents\GitHub\express-email-project\app.js:25:3
    at Layer.handle [as handle_request] (C:\Users\userpath\Documents\GitHub\express-email-project\node_modules\express\lib\router\layer.js:95:5)

**Comment by AvivLiberman** [comment]
Got the same error
